server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location / {
        return 302 /seller;
    }

    location /seller {
        try_files "/Apex Vision Vendedor.html" =404;
        add_header Cache-Control "no-cache, must-revalidate";
    }

    location /admin {
        try_files "/Apex Vision Console.html" =404;
        add_header Cache-Control "no-cache, must-revalidate";
    }

    location ~* \.(js|jsx|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        try_files $uri =404;
        add_header Cache-Control "no-cache, must-revalidate";
        expires -1;
    }
}
