server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index Apex Vision Vendedor.html;

    location / {
        try_files $uri $uri/ /index.html =404;
    }

    location ~* \.(html)$ {
        add_header Cache-Control "no-cache, must-revalidate";
    }
}
